# ______________________________________________________________________________________ 
# ______________________________________________________________________________________ 
# ______________________________________________________________________________________ 
# |                                                                                    |
# |          SCRIPT WRITTEN BY THOMAS DELATTRE thomas.delattre@inrae.fr              | 
# |                              ----------------                                      | 
# |                              LICENCE CC-BY-SA                                      | 
# |                              ----------------                                      |
# | This license lets others remix, adapt, and build upon your work even for           |
# | commercial purposes, as long as they credit you and license their new creations    |
# | under the identical terms.                                                         |
# |                                                                                    |
# | The proposed code has a purely academic purpose, is valid under the conditions     |
# | of use of the scientific project for which it was funded and at the date of        |
# | acceptance of the article presenting the code. As with any research work, the      |
# | code is not free of possible errors, approximations, sub-optimisations or          |
# | defects in monitoring dependencies between libraries of the program.               |
# |                                                                                    |
# ______________________________________________________________________________________ 
# |                                                                                    |
# | Cette licence permet à d'autres personnes de remixer, d'adapter et de              |
# | développer ce travail, même à des fins commerciales, à condition qu'elles          |
# | créditent l'auteur et accordent une licence pour leurs nouvelles créations aux     |
# | mêmes conditions.                                                                  |
# |                                                                                    |
# | Le code proposé a une visée purement académique, est valable dans les conditions   |
# | d'utilisation du projet scientifique pour lequel il a été financé et à la date de  |
# | d'acceptation de l'article de présentation du code.                                |
# | Comme tout travail de recherche, le code n'est pas exempt d'éventuelles erreurs,   |
# | approximations, sous-optimisations ou défauts de suivi des dépendances entre       |
# | sous-éléments du programme.                                                        |
# ______________________________________________________________________________________ 
# Objectif du script : 
# fonction d'export de fichiers sons sous la forme de sonagrammes animés au format vidéo
# Cette fonction est basée sur la démarche suivante : vous avez des enregistrements WildlifeAcoustics
# sur lesquels Birdnet a détecté des espèces. Vous réalisez ensuite une sélection de ces enregistrements
# pour une espèces donnée (wavTable). Après les avoir écouté, vous en sélectionnez certains pour
# les exporter en vidéo
# ______________________________________________________________________________________ 
# Usage : 
# source("/cheminDAcces/export_video_2.R")
# exportVideo(outputDir = "/path_to_export_folder/",
#             timeWindow = 10, #the length in seconds before and after begin and end time, to be exported. /!\ Be aware that it's a very long process that lengthen with timeWindow!
#             wavTable = nameOfTheTable, #needs to be a data.frame with columns Begin.File, Begin.Time..s., End.Time..s., Common.Name, as generated by Birdnet
#             wavList = c(23), #which sounds in the Table to you wan to export
#             suffix = "whatever",
#             beeep = TRUE) ; #sound signal at the end
# --------------------------------------------
# Changelog : 
# V1 = déploiement public initial
# --------------------------------------------


exportVideo = function (outputDir, timeWindow, wavTable, wavList, suffix, beeep) {
  
  #______________________________________________________________________
  # export VIDEO
  library(av)
  library(seewave)
  fenetre=timeWindow #rester prudent.es sur ce paramètre : l'export vidéo est très long
  output_dir=outputDir
  for(i in wavList) {
    selection=readWave(paste(wavTable$mydir[i],wavTable$Begin.File[i],sep=""),
                       from=wavTable$Begin.Time..s.[i]-fenetre,
                       to=wavTable$End.Time..s.[i]+fenetre,units="seconds")
    #norm=normalize(selection, unit="8",rescale = TRUE)
    
    #en cas de données faibles et bruitées (e.g. Trametes) :
    #spar détermine l'intensité du débruitage, mais attention à la perte de signal au-dessus de 0.4
    #normalize augmente l'intensité globale
    norm=normalize(rmnoise(selection,spar=0.4,output="Wave"), unit="8",rescale = TRUE)
    #norm=ffilter(norm, f = norm@samp.rate, from = 800, bandpass = TRUE, output = "Wave")
    #préparation du son, avec création d'un fichier temporaire à la racine de l'ordi
    writeWave(norm,"short_norm.wav")
    
    #préparation du son, avec création d'un fichier temporaire à la racine de l'ordi
    av_audio_convert(audio="short_norm.wav",#paste(Listen$mydir[i],Listen$Begin.File[i],sep=""),
                     output ='short.wav',
                     format="WAV",
                     sample_rate=16000,
                     #start_time = Listen$Begin.Time..s.[i]-fenetre,
                     #total_time = fenetre*2+1
    )
    
    #création de la vidéo-spectrogramme
    av_spectrogram_video('short.wav',
                         output = paste(output_dir,
                                        Listen$Begin.File[i],"_",
                                        Listen$Common.Name[i],
                                        "_",suffix,".mp4",sep=""),
                         width = 2560, height = 1440, res = 576, 
                         vfilter = 'framerate=fps=10')
  }
  if (beeep == TRUE) {listen( synth(d = 1, f = 44100, cf = 440, output = "Wave"))}
}
#----